In [5]:
import torch

In [6]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.shape 

torch.Size([12])

In [10]:
x.numel()

12

In [12]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
zeros = torch.zeros(2,3,4) 
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
ones = torch.ones(2,3,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
t1 = torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
t1

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [19]:
t1.shape

torch.Size([3, 3])

In [20]:
torch.exp(t1)

tensor([[   2.7183,    7.3891,   20.0855],
        [  20.0855,   54.5981,  148.4132],
        [ 148.4132,  403.4288, 1096.6332]])

In [21]:
t1.item()

ValueError: only one element tensors can be converted to Python scalars

In [26]:
A = torch.arange(40).reshape(2,4,5)
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 30,  34,  38,  42,  46]],

        [[110, 114, 118, 122, 126]]])

In [27]:
A/sum_A

tensor([[[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
         [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
         [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
         [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]],

        [[0.1818, 0.1842, 0.1864, 0.1885, 0.1905],
         [0.2273, 0.2281, 0.2288, 0.2295, 0.2302],
         [0.2727, 0.2719, 0.2712, 0.2705, 0.2698],
         [0.3182, 0.3158, 0.3136, 0.3115, 0.3095]]])

In [28]:
B = torch.arange(40).reshape(2,4,5)
sum_B = B.sum(axis=1)
sum_B

tensor([[ 30,  34,  38,  42,  46],
        [110, 114, 118, 122, 126]])

In [29]:
B/sum_B

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [31]:
torch.norm()

tensor(6.)

In [32]:
torch.ones((4,9))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
xx = torch.arange(4.0)
xx.requires_grad_(True)
y=2*torch.dot(xx,xx)
y.backward()
xx.grad == 4 * xx

tensor([True, True, True, True])

In [73]:
#xx.grad.zero_()
y=xx.sum()
y.backward()
xx.grad

tensor([ 1.,  5.,  9., 13.])